import { randomBytes } from 'node:crypto';
import { Schema, model, type HydratedDocument, type InferSchemaType } from 'mongoose';
import { USER_ROLES } from '../services/token.service.ts';

// Membership IDs are generated by the service, e.g. "MBR-3F9A1C07".
function generateMembershipId() {
  return `MBR-${randomBytes(4).toString('hex').toUpperCase()}`;
}

const userSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, unique: true, trim: true, lowercase: true },
    membershipId: {
      type: String,
      required: true,
      unique: true,
      immutable: true,
      default: generateMembershipId,
    },
    role: { type: String, enum: USER_ROLES, required: true, default: 'member' },
    // Excluded from queries unless asked for with .select('+passwordHash').
    passwordHash: { type: String, select: false },
  },
  {
    timestamps: true,
    optimisticConcurrency: true,
    toJSON: {
      virtuals: true,
      versionKey: false,
      transform: (_doc, ret: Record<string, unknown>) => {
        delete ret._id;
        delete ret.passwordHash; // Never sent to clients, even if it was loaded.
        return ret;
      },
    },
  },
);

userSchema.index({ name: 1 });

export type User = InferSchemaType<typeof userSchema>;
export type UserDocument = HydratedDocument<User>;

export const UserModel = model('User', userSchema);
