import { randomBytes } from 'node:crypto';
import { Schema, model, type HydratedDocument, type InferSchemaType } from 'mongoose';

// Membership IDs are generated by the service, e.g. "MBR-3F9A1C07".
function generateMembershipId() {
  return `MBR-${randomBytes(4).toString('hex').toUpperCase()}`;
}

const userSchema = new Schema(
  {
    name: { type: String, required: true, trim: true },
    email: { type: String, required: true, unique: true, trim: true, lowercase: true },
    membershipId: {
      type: String,
      required: true,
      unique: true,
      immutable: true,
      default: generateMembershipId,
    },
  },
  {
    timestamps: true,
    optimisticConcurrency: true,
    toJSON: {
      virtuals: true,
      versionKey: false,
      transform: (_doc, ret: Record<string, unknown>) => {
        delete ret._id;
        return ret;
      },
    },
  },
);

userSchema.index({ name: 1 });

export type User = InferSchemaType<typeof userSchema>;
export type UserDocument = HydratedDocument<User>;

export const UserModel = model('User', userSchema);
